export default function ExperiencePage() {
  const roles = [
    { title:"Data Analyst / BI Consultant", company:"Freelance / Consulting", dates:"Jun 2025 to Present", bullets:["Combined customer, sales, and operational records across five businesses, replacing manual data entry and giving teams one reliable source for daily business reporting.","Set up and improved customer management systems, including customer records, sales stages, follow-ups, and automated reminders, reducing manual data entry by 50%.","Analysed customer activity and purchase history to identify inactive, returning, and high-value customers, supporting changes that contributed to a 25% improvement in customer retention.","Built automated reports and dashboards showing sales, customer activity, revenue, and other agreed business measures, reducing the need to prepare reports manually.","Documented how customer and sales information was collected, updated, checked, and reported."] },
    { title:"Data Analyst, Risk & Security Intelligence", company:"Risk Control Services, Lagos, Nigeria", dates:"Feb 2025 to May 2025", bullets:["Combined and cleaned data from internal databases and SharePoint, reducing data errors by 40% and cutting processing time by 30%.","Coordinated a 5-member team handling data requests and client reports, reducing project turnaround time by 35%.","Built management dashboards and KPI reports showing security incidents, risk levels, and changes in key security measures for senior management.","Examined 300,000+ security records to identify unusual activity and recurring risk patterns, improving threat-detection precision by 25%."] },
    { title:"Data Analyst", company:"Instinct Hub, Lagos, Nigeria", dates:"2023 to 2024", bullets:["Analysed customer activity and account history to identify customers likely to stop using the service, reducing manual customer tracking time by 20%.","Built automated reports that reduced the time required to prepare recurring reports and contributed to a 15% improvement in team efficiency.","Delivered six analytics workshops for 8+ analysts covering data cleaning, analysis, reporting, and chart design, contributing to a 28% improvement in reporting accuracy.","Mentored eight junior analysts on SQL, Python, and data visualisation, reviewing their work and correcting errors in queries, analysis, and reports."] },
    { title:"Business/Data Analyst", company:"Adullam Technologies Limited, Lagos, Nigeria", dates:"2022 to 2023", bullets:["Reviewed stock levels and sales records to identify products with excess inventory, helping reduce overstock by 15%.","Analysed customer purchase records to group customers by buying frequency and spending, supporting targeted marketing that increased customer loyalty by 25%.","Documented sales, inventory, and customer processes from start to finish, identifying duplicated steps, missing procedures, and points where work was being delayed."] }
  ];
  return <main><section className="section"><div className="container"><div className="eyebrow">Experience</div><h1>Professional experience.</h1><p className="lead">Four roles covering business intelligence, customer analytics, risk and security intelligence, reporting, data quality and operational analysis.</p><div style={{display:"grid",gap:18,marginTop:40}}>{roles.map(r=><article className="card" key={r.title+r.company}><h2 style={{fontSize:"1.55rem"}}>{r.title}</h2><p className="small">{r.company} · {r.dates}</p><ul className="case-list">{r.bullets.map(b=><li key={b}>{b}</li>)}</ul></article>)}</div><div className="actions" style={{marginTop:35}}><a className="btn btn-primary" href="/cv/Daniel_Olatunji_CV.pdf" download>Download CV</a></div></div></section></main>;
}
