import Link from "next/link";

export const metadata = {
  title: "About | Daniel Olatunji",
  description: "Daniel Olatunji is a Data Analyst and Business Intelligence Analyst working across revenue, customer, risk and operational analysis.",
  alternates: { canonical: "https://daniel-olatunji-portfolio.vercel.app/about" },
  openGraph: { title: "About | Daniel Olatunji", description: "Data analysis and business intelligence experience across revenue, customer, risk and operational problems.", url: "https://daniel-olatunji-portfolio.vercel.app/about", images: ["/og-image.svg"] },
};

const skills = [
  ["Data Analysis & Statistics", "SQL, Python, R, hypothesis testing, regression, forecasting"],
  ["Business Intelligence", "Power BI, Excel, Power Query, DAX, Tableau, Looker Studio, KPI reporting"],
  ["Data Preparation & Quality", "SQL, ETL, data validation, data cleaning, relational modelling, PostgreSQL"],
  ["Revenue & Customer Analysis", "Revenue analysis, customer segmentation, retention, pipeline and channel performance"],
  ["Business Analysis", "KPI definition, process mapping, requirements analysis and analytical reporting"],
];

export default function AboutPage() { return <main>
  <section className="section"><div className="container two-col"><div><div className="eyebrow">About Daniel</div><h1>Data analysis built around business questions.</h1></div><div><p className="lead">I am a Data Analyst with 4+ years of experience using data to investigate revenue, customer, risk and operational problems.</p><p>I build reporting models, dashboards and analysis that explain what changed, where the problem sits and what the business should investigate next. My work includes datasets with millions of records, customer analysis, data quality, forecasting and reporting.</p><p>My main focus is data analysis and business intelligence. I also work with CRM data and reporting processes when they are part of the business problem being analysed.</p><div className="actions"><a className="btn btn-primary" href="/cv/Daniel_Olatunji_CV.pdf" download>Download CV</a><Link className="btn btn-secondary" href="/work">View My Work</Link></div></div></div></section>
  <section className="section-tight"><div className="container"><div className="eyebrow">Experience</div><h2>Where I have done this work.</h2><div className="three-grid"><div className="card"><h3>Data Analyst / BI Consultant</h3><p className="small">Freelance / Consulting · Jun 2025 – Present</p><p>Combined customer, sales and operational records across five businesses, built reporting and dashboards, analysed customer behaviour and improved customer data processes.</p><div className="proof-grid" style={{gridTemplateColumns:"1fr 1fr"}}><div className="proof-card"><strong>50%</strong><span>less manual data entry</span></div><div className="proof-card"><strong>25%</strong><span>customer-retention improvement</span></div></div></div><div className="card"><h3>Data Analyst, Risk & Security Intelligence</h3><p className="small">Risk Control Services · Feb 2025 – May 2025</p><p>Combined and cleaned internal and SharePoint data, built management dashboards and examined 300,000+ security records for unusual activity and recurring risk patterns.</p><div className="tag-list"><span className="tag">40% fewer data errors</span><span className="tag">30% faster processing</span><span className="tag">35% faster turnaround</span></div></div><div className="card"><h3>Data Analyst</h3><p className="small">Instinct Hub · 2023 – 2024</p><p>Analysed customer activity and account history, built automated reports, delivered six analytics workshops for 8+ analysts and mentored eight junior analysts.</p></div><div className="card"><h3>Business / Data Analyst</h3><p className="small">Adullam Technologies Limited · 2022 – 2023</p><p>Reviewed stock and sales records, helped reduce overstock by 15%, analysed customer buying behaviour and documented sales, inventory and customer processes.</p></div></div></div></section>
  <section className="section"><div className="container"><div className="eyebrow">Core skills</div><h2>What I work with.</h2><div className="three-grid">{skills.map(([a,b])=><div className="card" key={a}><h3>{a}</h3><p>{b}</p></div>)}</div></div></section>
  <section className="section-tight"><div className="container two-col"><div><div className="eyebrow">Education</div><h2>Statistics foundation.</h2></div><div className="card"><h3>B.Sc. in Statistics</h3><p>University of Lagos, Nigeria · 2021</p></div></div></section>
  <section className="section-tight"><div className="container"><div className="eyebrow">Certifications</div><h2>Certifications</h2><div className="four-grid">{[["IBM Data Science Professional Certificate","2024"],["Scrum Business Analysis Certification","2024"],["Google Data Analytics Professional Certificate","2023"],["Forage Data Analytics Consulting Program","2023"]].map(([a,b])=><div className="card" key={a}><h3>{a}</h3><p>{b}</p></div>)}</div></div></section>
</main>; }