import Link from "next/link";
import { projects } from "@/lib/projects";

const focus = [
  ["Data Analysis","I analyse business data to understand performance, customer behaviour, revenue, risk and operational problems."],
  ["Business Intelligence","I build reporting that makes important business information easier to understand."],
  ["Data Quality & ETL","I clean, check and structure data before it is used for reporting or analysis."],
  ["CRM Data","I work with customer, company, contact and sales data to improve data quality, migration and reporting."],
  ["Automation","I automate repetitive reporting and operational processes where manual work creates unnecessary effort or errors."]
];
const services = [
  ["Business Reporting & Dashboards","Turn scattered business data into clear reporting for sales, revenue, customers and operations."],
  ["Data Cleaning & Quality","Find duplicates, missing information, inconsistent records and other problems before they affect reporting."],
  ["CRM Data & Migration","Clean, organise and prepare CRM data for migration, reporting and ongoing use."],
  ["Revenue & Customer Analysis","Analyse revenue, customer behaviour, pipeline, retention and channel performance."],
  ["Operational Analytics","Use data to investigate inventory, delivery, workforce, cost and process problems."],
  ["Workflow Automation","Reduce repetitive manual work by connecting business systems, spreadsheets and workflows."]
];
export default function Home() { return <main>
  <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow">Data · Reporting · CRM · Automation</div><h1>Daniel Olatunji</h1><p style={{fontSize:"1.45rem",color:"#f3f1ea"}}>Data Analyst | Business Intelligence Analyst</p><p>I clean up messy data, fix reporting problems, automate repetitive work, and build practical systems that help businesses understand performance and act on it.</p><div className="actions"><Link className="btn btn-primary" href="/work">View My Work</Link><Link className="btn btn-secondary" href="/contact">Contact Me</Link><a className="btn btn-secondary" href="https://github.com/oreoluwadaniel" target="_blank" rel="noreferrer">View GitHub</a></div></div><div className="portrait"><img src="/images/IMG_4720.JPG" alt="Daniel Olatunji" style={{width:"100%",height:"100%",objectFit:"cover"}} /></div></div></section>
  <section className="section-tight"><div className="container"><div className="eyebrow">Work snapshot</div><h2>Business questions first. Tools second.</h2><div className="proof-grid">{[["Revenue Analytics","Revenue, customers, pipeline and retention."],["Data Quality","Duplicates, missing information and exceptions."],["Business Intelligence","Reporting built around real business questions."],["CRM Data","Customer, company, contact and deal records."],["Automation","Repetitive reporting and operational work."]].map(([a,b])=><div className="proof-card" key={a}><strong>{a}</strong><span>{b}</span></div>)}</div></div></section>
  <section className="section"><div className="container"><div className="eyebrow">What I work on</div><h2>Data work that has a business reason behind it.</h2><div className="three-grid">{focus.map(([a,b])=><div className="card" key={a}><h3>{a}</h3><p>{b}</p></div>)}</div></div></section>
  <section className="section-tight"><div className="container"><div className="eyebrow">Selected work</div><h2>Projects with the problem, data and reasoning behind the result.</h2><div className="project-grid">{projects.map(p=><article className="card project-card" key={p.slug}><img className="cover" src={p.cover} alt={`${p.title} project cover`} /><div className="content"><div className="meta">{p.category}</div><h3>{p.title}</h3><p>{p.short}</p><div className="small">{p.scale}</div><div className="tag-list">{p.tools.slice(0,4).map(t=><span className="tag" key={t}>{t}</span>)}</div><div className="card-actions"><Link className="btn btn-primary" href={`/work/${p.slug}`}>Read Case Study</Link><a className="btn btn-secondary" href={p.github} target="_blank" rel="noreferrer">GitHub</a></div></div></article>)}</div></div></section>
  <section className="section"><div className="container"><div className="eyebrow">How I work</div><h2>A simple process for getting from a business question to a useful answer.</h2><div className="steps">{[["01","Understand the question","Start with the business problem rather than the software."],["02","Check the data","Look for missing, duplicate, inconsistent or unreliable information."],["03","Clean and structure it","Prepare the data so it can be analysed properly."],["04","Analyse and check","Look for patterns, relationships and problems, then verify important results."],["05","Explain what matters","Translate the numbers into plain business language."],["06","Make useful work repeatable","Automate repetitive reporting or operational tasks where it makes sense."]].map(([n,a,b])=><div className="card step" key={n}><div className="num">{n}</div><h3>{a}</h3><p>{b}</p></div>)}</div></div></section>
  <section className="section-tight"><div className="container"><div className="eyebrow">Services</div><h2>What I can help with.</h2><div className="service-grid">{services.map(([a,b])=><div className="card" key={a}><h3>{a}</h3><p>{b}</p><Link href="/contact" className="small">Discuss a project →</Link></div>)}</div></div></section>
  <section className="section"><div className="container two-col"><div><div className="eyebrow">About</div><h2>A practical approach to data.</h2></div><div><p className="lead">I work at the point where data, reporting, CRM and business operations meet. My work involves cleaning unreliable data, building reporting systems, analysing business performance and automating repetitive processes.</p><p>Across my projects, I have worked on revenue analysis, retail analytics, CRM data, data quality, ETL, logistics, forecasting and operational workflows.</p><div className="actions"><Link className="btn btn-secondary" href="/about">Read More</Link><a className="btn btn-secondary" href="/cv/Daniel_Olatunji_CV.pdf" download>Download CV</a></div></div></div></section>
  <section className="section-tight"><div className="container"><div className="eyebrow">Writing</div><h2>Writing & analysis</h2><p className="lead">I also write about data analysis, business problems and technical subjects in plain language.</p><div className="three-grid">{["A Day in the Life of a Data Analyst","Why Moving Your Desktop Workloads to Azure Makes Complete Sense","Exploring Crime Data with Python"].map(t=><a className="card" key={t} href="https://medium.com/@oluwafikayore" target="_blank" rel="noreferrer"><h3>{t}</h3><p>Read on Medium →</p></a>)}</div></div></section>
  <section className="section"><div className="container contact-box"><div><div className="eyebrow">Contact</div><h2>Have a data, reporting or process problem?</h2><p className="lead">If the data is messy, the reporting is unreliable, the CRM needs cleaning, or a repetitive process needs automating, tell me what is going on.</p><a className="btn btn-primary" href="mailto:danolatunji25@gmail.com">danolatunji25@gmail.com</a></div><div><Link className="btn btn-secondary" href="/contact">Send an enquiry →</Link></div></div></section>
</main>; }
