export type Project = {
  slug: string;
  title: string;
  category: string;
  short: string;
  status: string;
  cover: string;
  github: string;
  scale: string;
  tools: string[];
  context: string;
  problem: string;
  objective: string;
  questions: string[];
  data: string[];
  work: string[];
  workflow: string[];
  findings: string[];
  meaning: string;
  recommendations: string[];
  judgement: string;
};

export const projects: Project[] = [
  {
    slug: "bloomcrest-revenue-intelligence",
    title: "Bloomcrest Revenue Intelligence",
    category: "Revenue & Customer Analytics",
    short: "Sales, customers, deals and payments brought into one view. 6,129 customers had gone quiet and the monthly report had not noticed.",
    status: "Synthetic data · Fictional business",
    cover: "/project-covers/bloomcrest.svg",
    github: "https://github.com/oreoluwadaniel/bloomcrest-revenue-intelligence",
    scale: "18,000 customers · 360 wholesale deals · NGN 7.353B revenue · Jul 2024 to Jul 2026",
    tools: [
      "PostgreSQL",
      "SQL",
      "Python",
      "pandas",
      "HubSpot",
      "Make.com",
    ],
    context: "Bloomcrest sells directly to shoppers and in bulk to wholesale accounts. Sales, customer records, the deal pipeline and the payments ledger each sat in a different place. Each one reported honestly on its own, and nobody could see the four together.",
    problem: "A revenue leader gets asked the same five questions every month, and every one of them needs data from a different system. Are we on target. Which deals need attention. Which customers have stopped buying. How much of what we invoiced has actually arrived. Where is money leaking out. Four separate reports give four defensible answers and no decision.",
    objective: "Put every customer, order, deal and payment into one place, then answer those five questions from a single set of numbers everyone in the room can agree on.",
    questions: [
      "Are we on track against the revenue target?",
      "Which deals need attention this week?",
      "Which customers have gone quiet?",
      "How much of what we invoiced has actually been paid?",
      "Where is money leaking out of the process?",
    ],
    data: [
      "18,000 customers",
      "360 wholesale deals",
      "NGN 7.353 billion in revenue, 43.6% from direct sales and 56.4% from wholesale",
      "Two years of trading, July 2024 to July 2026",
      "Synthetic data built to behave like a real trading business",
    ],
    work: [
      "Brought customer, order, deal and payment records into one database so they could be read against each other.",
      "Matched the sales system's company names to the customer records, and set the accounts that would not match cleanly aside for review instead of forcing them together.",
      "Measured revenue, new customers, repeat buying and cash collected over the same periods.",
      "Scored every customer on how recently they bought, how often, and how much, then grouped them by how much revenue was at risk.",
      "Connected the systems so the numbers refresh without anyone re-exporting spreadsheets.",
      "Built a customer scoring model, tested it against guesswork, and acted on the result.",
    ],
    workflow: [
      "Bring the data together",
      "Match the records",
      "Measure revenue and cash",
      "Score the customers",
      "Test the model",
      "Report",
    ],
    findings: [
      "Revenue came to NGN 7.353 billion, split 43.6% direct to shoppers and 56.4% wholesale. Neither side can be run as the afterthought.",
      "Just under half of all deals closed, 48.6%, and a won deal took about 41.5 days from first contact to signature. Sales now has a planning number instead of a hopeful one.",
      "Open deals were worth NGN 129.44 million on paper. Weighted by how likely each one was to actually close, they were worth NGN 55.09 million. The gap between those two figures is the difference between a forecast and a wish.",
      "6,129 of 18,000 customers, just over a third, had not placed a successful order in 90 days. Total revenue had not fallen, so nothing in the monthly report had flagged it.",
      "3,884 of those quiet customers account for about NGN 819 million of past orders. That is the money most at risk, and it is now a named list of accounts rather than a general worry.",
      "The customer scoring model was tested and it ranked customers worse than picking names at random. It was not put into use, and the result is published here rather than buried.",
    ],
    meaning: "Joining the systems was never about a tidier report. It was about getting the pipeline number, the cash collected number and the quiet customer count to contradict each other in front of the same people. Once 6,129 quiet customers sit next to a healthy revenue line, somebody has to explain the difference, and that is the conversation where a decision actually gets made.",
    recommendations: [
      "Forecast on the weighted figure of NGN 55.09 million, and keep the NGN 129.44 million headline out of any commitment conversation.",
      "Work the 3,884 at-risk customers before spending on finding new ones. That revenue is already proven and cheaper to win back.",
      "Report the 90-day quiet customer count weekly. It moves months before total revenue does.",
      "Show invoiced revenue and collected revenue as two separate lines, permanently.",
      "Do not put the customer scoring model into use. Rebuild it on different inputs or drop the idea.",
    ],
    judgement: "The scoring model was the part I most wanted to work, and it ranked customers worse than chance. I left it out of the system and left the number on the page. A portfolio that only shows what worked tells you nothing about how the person works.",
  },
  {
    slug: "crestline-inventory-decision-support",
    title: "Crestline Inventory Decision Support",
    category: "Inventory & Working Capital",
    short: "A bulk purchase booked as a ₦9m saving actually cost ₦8.4m once somebody counted what it costs to store stock.",
    status: "Synthetic data · Fictional business",
    cover: "/project-covers/crestline.svg",
    github: "https://github.com/oreoluwadaniel/crestline-inventory-decision-support",
    scale: "5 warehouses · 7 conditions modelled · ₦412.4M stock on hand · position as at June 2026",
    tools: [
      "Excel",
      "Power Query",
      "Scenario Modelling",
      "Forecasting",
    ],
    context: "Crestline runs five warehouses in Nigeria. Every month a buyer decides how much stock to order, and that decision is made against a report describing what already happened, with no way to test what a change in demand, supplier delays or the exchange rate would do to the cash position.",
    problem: "Order too much and cash sits on a shelf. Order too little and sales walk away. Buyers settle that argument on unit price, because unit price is the only number in front of them, and it is the number that misleads most often.",
    objective: "Build a model where a buyer changes one condition, then sees straight away what happens to stock value, service to customers, cost and cash, measured against a normal month.",
    questions: [
      "What happens to stock and cash if suppliers start taking twice as long?",
      "What if demand jumps 30%, or falls 15%?",
      "What does a 12% supplier price rise, or a 20% jump in imported costs, do to the position?",
      "Is a bulk discount still worth taking once the extra stock has to be stored and paid for?",
    ],
    data: [
      "Five warehouses, a fictional Nigerian distributor",
      "Sales, purchase orders, stock transfers, returns, stock counts, storage and transport costs",
      "Position as at June 2026",
      "Seven conditions modelled: normal month, supplier delays, demand spike, demand fall, cost rise, currency pressure, bulk discount",
      "Synthetic data built to behave like a real distributor",
    ],
    work: [
      "Rebuilt the stock position from individual transactions rather than trusting a monthly summary.",
      "Worked out how much to order and how much buffer stock to hold against a stated service target.",
      "Costed the money tied up in stock properly, including the cost of borrowing it.",
      "Built a switch that recalculates the whole dashboard against any of the seven conditions.",
      "Went back to a bulk purchase the business had already made and treated as a win.",
      "Marked every assumption that was an estimate rather than a confirmed figure.",
    ],
    workflow: [
      "Rebuild the stock position",
      "Cost the money tied up",
      "Set the ordering rules",
      "Model the conditions",
      "Compare to a normal month",
      "Report",
    ],
    findings: [
      "A bulk purchase recorded internally as a ₦9,000,000 saving was a ₦8,400,000 loss. The 12% discount on a ₦75,000,000 order brought in eight months of stock, and holding it for eight months costs 23% of its value, ₦17,400,000, against the ₦9,000,000 saved.",
      "That loss is still understated. It does not count the warehouse space the stock blocked, which could have held goods that were actually selling.",
      "Holding stock costs 35% a year here: 28% borrowing cost, 1% insurance, 6% storage, spoilage and theft. The previous estimate of 20% to 25% left the borrowing cost out entirely, which is exactly why the bulk deal looked like a win.",
      "₦28,660,219 of stock, 6.9% of the ₦412,412,369 held, has more than six months of cover behind it. That is the single largest pot of cash available to release, and releasing it costs nothing.",
      "Orders arriving complete and on time run at 70.5% against a 90% target, while item availability is 97.5% against a 95% target. The business is reporting the number that looks good. Customers experience the other one.",
      "Lagos Main is 77% full, the fullest site in the network. Any decision to buy more has to answer where it goes before it answers what it costs.",
      "Stock turns over 12.4 times a year and sits for 29 days on average. Stock value is 1.2% above target after rising 6.6% in a month, so the position is drifting the wrong way.",
    ],
    meaning: "The bulk deal is the case that pays for the whole model. The ₦9,000,000 saving was real and it was reported accurately. It was still the wrong decision, because the cost of holding the stock was never in the room when the decision was made. A discount is only a saving if you are not paying to store it.",
    recommendations: [
      "Put every bulk offer through total cost before approval rather than discount percentage. This one would have been turned down.",
      "Get finance to sign off the 35% holding cost, because it changes which purchases pass and which do not.",
      "Release the ₦28.66 million sitting in six months or more of cover first. It is the largest recoverable amount and it needs no new spending.",
      "Fix delivery reliability at 70.5% before anyone celebrates 97.5% availability. Customers only see the first number.",
      "Move stock out of Lagos Main at 77% full before the next demand increase turns it into a constraint.",
    ],
    judgement: "I recalculated the cost of holding stock before running a single scenario. The old estimate left out the cost of borrowing the money, and at 28% that omission is the entire difference between a ₦9 million saving and an ₦8.4 million loss. Getting one assumption right mattered more than every scenario built on top of it.",
  },
  {
    slug: "ab-testing-experimentation",
    title: "A/B Testing & Product Experimentation",
    category: "Experimentation & Product Analytics",
    short: "Two product tests taken to a release-or-hold decision. The winner came with a catch worth more than the win.",
    status: "Synthetic test data · Two linked cases",
    cover: "/project-covers/abtesting.svg",
    github: "https://github.com/oreoluwadaniel/ab-testing-case-studies",
    scale: "8,200 website visitors over 42 days · 7,500 new app users",
    tools: [
      "Python",
      "pandas",
      "SciPy",
      "statsmodels",
      "Power BI",
    ],
    context: "Two teams wanted to release a change. One had redesigned a landing page. The other had built a guided setup assistant into a mobile app. Both had run a test, and both tests showed their version ahead.",
    problem: "A version can be ahead by luck, or ahead by an amount too small to be worth building. And if you only measure the people who chose to use a new feature, you are answering an easier question than the one that was asked, and getting a friendlier answer to it.",
    objective: "Take both tests to a yes or a no. Check the test was set up fairly, measure how much better the new version really is, say how confident that is, check it holds for different kinds of user, and give a straight recommendation.",
    questions: [
      "Were people split fairly between the two versions?",
      "How much better is the new version, and what is the realistic range?",
      "Does the result hold on phones as well as desktops?",
      "Are we measuring everyone shown the change, or only the people who chose to use it?",
      "Is the improvement big enough to be worth releasing?",
    ],
    data: [
      "Landing page: 8,435 visits from 8,200 people, 4,120 on the old page and 4,080 on the new one",
      "Landing page test ran 42 days, 18 May to 28 June 2026",
      "App: 7,500 new users, 3,714 on the old setup and 3,786 on the new one",
      "Five app versions and two phone types covered",
      "Synthetic test data built to behave like real product data",
    ],
    work: [
      "Counted each visitor once rather than each visit, so a person who came back three times did not count three times.",
      "Measured the gap between the two versions, and how likely a gap that size was to be luck.",
      "Reported the realistic range around every result alongside the headline figure.",
      "Checked the result held across devices and traffic sources before trusting it.",
      "Measured everyone who was shown the change, and treated the behaviour of people who chose to use it as separate and weaker evidence.",
      "Checked the test had enough people in it to detect a difference worth acting on.",
    ],
    workflow: [
      "Frame the decision",
      "Check the test was fair",
      "Count people, not visits",
      "Measure the gap",
      "Check it holds",
      "Recommend",
    ],
    findings: [
      "The new landing page converted 4.44% of visitors against 3.08% for the old one. That is 1.35 more customers in every hundred visitors, a 43.9% improvement. A gap this size would come up by chance about once in 800 tests, and the realistic range is between 0.5 and 2.2 extra customers per hundred.",
      "Visitor behaviour backs the conversion number up rather than leaving it standing alone. People left immediately 58.8% of the time on the new page against 65.5% on the old, and stayed 37.3 seconds against 30.5.",
      "Counting visits instead of people changes the answer. The same data read visit by visit shows 4.04% against 2.94%, a different sized win produced by a wrong way of counting.",
      "In the app, 40.65% of new users were still active after seven days against 36.54% before, so 4.11 more users kept in every hundred. A gap this size would come up by chance about once in 3,000 tests.",
      "Only 37.8% of the users shown the setup assistant ever opened it. Of those who did, 50.5% were still active after seven days. Of those who never opened it, 34.6% were, which is below the 36.54% for users who never had it at all.",
      "That split is the finding worth acting on. The entire improvement is coming from a third of the users. The assistant is not the problem. Getting people to open it is.",
    ],
    meaning: "Both changes are worth releasing. The app test also hands the product team a better question than the one they brought. If a third of users opening the assistant produces 4.11 extra retained users per hundred, the value sitting in the two thirds who never open it is larger than the value already collected.",
    recommendations: [
      "Release the landing page for the traffic that was tested, and keep watching conversion after launch.",
      "Release the setup assistant, then make getting people to open it the next piece of work. That is where the remaining value sits.",
      "Do not quote the 50.5% figure as the effect of the assistant. Those users chose to open it, and that choice says something about them as well as about the feature.",
      "Agree the smallest improvement worth releasing before the test runs, not after the result arrives.",
      "Decide whether you are counting people or visits before the test starts. The same data gives two different answers.",
    ],
    judgement: "The app test was a clean win and I did not report it as one. Users who were shown the assistant and ignored it stayed at 34.6%, below the users who never had it at all. The honest read is that the benefit sits with a third of the group, and the real product question is exposure rather than the feature.",
  },
  {
    slug: "weatherintel",
    title: "WeatherIntel: Weather Data & Forecast Testing",
    category: "Forecasting & Data Pipelines",
    short: "371,482 days of weather readings checked for quality, then four forecasting methods raced. The complicated one won by 0.11°C.",
    status: "Public source data · Real weather records",
    cover: "/project-covers/weatherintel.svg",
    github: "https://github.com/oreoluwadaniel/weatherintel-global-weather-analytics",
    scale: "8 weather stations · 4 continents · 371,482 days of readings · records back to 1763",
    tools: [
      "Python",
      "PostgreSQL",
      "SQL",
      "XGBoost",
      "Power BI",
    ],
    context: "Farms, airlines, insurers, hauliers and power companies all plan against past weather. The archives they plan from contain missing days, readings the recording station itself marked as doubtful, and stations that stop and start without warning.",
    problem: "Two things go wrong here and they compound. Readings that never passed a quality check get treated as fact, and a forecast that was never raced against anything gets treated as skill. Either one gives you a confident plan resting on nothing.",
    objective: "Keep the raw readings and the checked readings apart so it is always obvious which is being used. Then race four forecasting methods against each other on days none of them had seen, and publish all four scores.",
    questions: [
      "Which readings can actually be trusted?",
      "What do the patterns look like once the bad readings are out?",
      "Does the complicated method beat simply repeating yesterday's temperature?",
      "Is it enough better to be worth running and maintaining every day?",
    ],
    data: [
      "Public weather station records from the US National Oceanic and Atmospheric Administration",
      "8 stations across 4 continents",
      "371,482 days of readings that passed the quality checks",
      "History from 1763 to March 2018, depending on the station",
      "Real public data, not synthetic",
    ],
    work: [
      "Read the raw station files and put them into one consistent format.",
      "Kept the quality warnings the stations themselves recorded rather than dropping them on the way in.",
      "Removed readings that failed the checks, and kept a record of every one removed.",
      "Stored the checked readings in a database built for querying.",
      "Examined temperature and rainfall patterns station by station.",
      "Raced four forecasting methods on the same unseen days: a machine learning model, a straight-line method, repeating yesterday's reading, and the long-run average for that date.",
    ],
    workflow: [
      "Read the raw files",
      "Keep the quality warnings",
      "Remove failed readings",
      "Store the clean data",
      "Race four methods",
      "Report",
    ],
    findings: [
      "The machine learning model was the most accurate, missing by 2.22°C on average. Simply repeating yesterday's temperature missed by 2.33°C, and a straight-line method missed by 2.25°C.",
      "So the model beats yesterday's reading by 0.11°C. That is a real improvement and a small one, and somebody has to run and maintain the model every day to keep it.",
      "The straight-line method lands within 0.03°C of the machine learning model. For most planning decisions it is the better choice, because it is far simpler to run and to explain to the people relying on it.",
      "Planning against the long-run average for the date is much worse, missing by 4.81°C. That is the option that actually costs money, and it is the one most businesses default to.",
      "371,482 days of readings survived the quality checks across 8 stations. Every reading removed is still traceable, so anyone can see what was taken out and why.",
      "Station histories differ by more than two hundred years, so comparing one station against another needs the length of the record read alongside the number.",
    ],
    meaning: "The interesting result is not that the machine learning model won. It is that it won by 0.11°C over repeating yesterday's reading. That single number is what a planning team actually needs, because it is what tells them whether the model is worth owning. On this evidence, for most uses, it is not.",
    recommendations: [
      "Keep raw readings and checked readings in separate places, permanently. Once they mix, nobody can tell which was used.",
      "Record the reason every reading was removed, so the exclusions can be argued with rather than taken on trust.",
      "Race every forecast against simply repeating the last reading before adopting it. It is a cheap comparison and it changes decisions.",
      "Use the straight-line method rather than the machine learning model unless the 0.03°C difference matters for what is being decided.",
      "Publish the forecast's average error next to the forecast, so the reader knows how much room to leave around it.",
    ],
    judgement: "I published the scores for the simple methods even though they made the model look ordinary. A forecast earns its place by beating something simple on days it has never seen, and 0.11°C is honestly what it earned.",
  },
  {
    slug: "data-analytics-etl",
    title: "Data Quality & Business Reporting",
    category: "Data Quality & Reporting",
    short: "Four reporting systems where nearly a third of customer records failed the checks. They were sent for review, not quietly deleted.",
    status: "Synthetic data · Four linked cases",
    cover: "/project-covers/etl.svg",
    github: "https://github.com/oreoluwadaniel/data-analytics-etl-portfolio",
    scale: "5,130 customer records · 1,001 employees · 3,400 products · 75,000 sales",
    tools: [
      "Excel",
      "Power Query",
      "Power Pivot",
      "SQL",
      "VBA",
    ],
    context: "A duplicated customer inflates a sales pipeline. An employee with no manager on file distorts a headcount report. Stock recorded as a negative number hides a real shortage. A sale dated next month makes this month look better than it was. All four pass straight into a dashboard without complaint.",
    problem: "Cleaning data usually means making the errors disappear. That destroys the most useful thing in the file, which is the fact that a record was wrong in the first place. Very often that fact is the finding management most needed.",
    objective: "Build four reporting systems where anything failing a check goes to a review list and gets counted, so every published number arrives with a clear statement of what was left out and why.",
    questions: [
      "Which records are safe to put in front of management?",
      "Which ones need a person to look at them?",
      "Which missing information is a business problem rather than a data problem?",
      "Can the report explain what it left out?",
    ],
    data: [
      "Customer records: 5,130",
      "Employees: 1,001, across payroll, attendance, leave and performance files",
      "Products: 3,400",
      "Sales: 75,000 transactions from 13 branches",
      "Synthetic data built to contain the faults real business exports contain",
    ],
    work: [
      "Examined each source file and scored how complete it was before changing anything.",
      "Wrote out the rules a record has to pass, then sent every failure to a review list instead of deleting it.",
      "Combined payroll, attendance, leave and performance into one employee view while leaving the gaps visible.",
      "Ran 15 checks on the stock file before building the reordering view.",
      "Standardised 13 branch sales files into one, with the checks applied before any number reached a report.",
      "Counted every final figure back to the source and published the difference.",
    ],
    workflow: [
      "Examine the source",
      "Score completeness",
      "Apply the rules",
      "Send failures to review",
      "Build the report",
      "Count back to source",
    ],
    findings: [
      "1,555 of 5,130 customer records, 30.3%, failed the checks. Every one went to a review list rather than being deleted, so the sales team can see exactly which accounts they cannot rely on.",
      "301 employees have no performance review on file and 464 have no manager recorded. Those are not data problems. 464 people with nobody accountable for them is a management problem that a tidy report would have hidden.",
      "The stock analysis found ₦6.49 billion of reordering exposure across 3,400 products. That is money at risk of being committed, not money saved, and the report says so on its face.",
      "74,598 of 75,000 sales transactions were accepted into reporting. The 402 rejected are accounted for one by one, so when someone asks why the total does not match the raw file, there is an answer ready.",
      "The payroll file held 1,016 rows for 1,001 people. Fifteen duplicated rows is exactly the sort of quiet error that inflates a headcount report and that nobody catches.",
    ],
    meaning: "Keeping the failures visible is the entire point. 464 employees with no manager on record is not noise to be tidied away before the dashboard renders. It is a finding. Deleting it produces a cleaner report about a business that is now less well understood than it was before.",
    recommendations: [
      "Send failed records to a review list and report the count. Never delete them quietly.",
      "Treat the 464 employees without a manager as an ownership problem, with a named owner and a date.",
      "Run the checks before the report is built, not after somebody questions a number in a meeting.",
      "Count the final figures back to the source on every refresh and publish the difference.",
      "Put the exclusion rate on the report itself, so whoever reads it knows what the number covers.",
    ],
    judgement: "I kept the failures visible. A blank manager field, a negative stock figure or a customer record that fails a check is information about the business, not a reason to quietly drop a row.",
  },
];
