export type Project = {
  slug: string;
  title: string;
  category: string;
  short: string;
  status: string;
  cover: string;
  github: string;
  scale: string;
  tools: string[];
  context: string;
  problem: string;
  objective: string;
  questions: string[];
  data: string[];
  work: string[];
  workflow: string[];
  findings: string[];
  meaning: string;
  recommendations: string[];
  output: string;
  limitations: string[];
  judgement: string;
};

export const projects: Project[] = [
  {
    slug: "everdale-retail-analytics",
    title: "Everdale Retail Analytics",
    category: "Retail Analytics · Business Intelligence",
    short: "194,480 order lines rebuilt at the right grain, so revenue growth could finally be separated from profitable growth.",
    status: "Synthetic data · Fictional business",
    cover: "/project-covers/everdale.svg",
    github: "https://github.com/oreoluwadaniel/everdale-retail-analytics",
    scale: "194,480 order-line records · 13 source tables · Jan 2023 to Dec 2025",
    tools: [
      "Excel",
      "Power Query",
      "Power Pivot",
      "DAX",
      "Statistical Forecasting",
    ],
    context: "Everdale is a fictional Nigerian retailer selling through physical stores and an online channel. Management received a sales figure every month and almost nothing behind it. The question they kept returning to was whether the growth on the top line still meant anything by the time it reached profit.",
    problem: "Order-level facts and order-line facts sat in the same reporting model. Any measure that touched both counted the same money more than once on multi-line orders, so channel and category comparisons were wrong in a way no one could see from the dashboard.",
    objective: "Rebuild the model at one row per order line, then use it to answer four questions: where profit actually comes from, how much revenue depends on discount, how the two channels compare once the arithmetic is right, and whether three years of history supports a forecast worth planning against.",
    questions: [
      "Is online growth adding profit, or adding volume at a thinner margin?",
      "Which categories lead on revenue but not on margin?",
      "How much of the revenue is bought with discount?",
      "How does demand shift around salary weeks, Black Friday, December and Ramadan?",
      "Do three years of history support a forecast management can plan against?",
    ],
    data: [
      "194,480 order-line records",
      "13 source tables",
      "January 2023 to December 2025",
      "Nigerian omnichannel retail, values in NGN",
      "Synthetic data, built to carry the defects real retail exports carry",
    ],
    work: [
      "Profiled all 13 source tables and recorded the grain of each one before loading anything.",
      "Separated order header facts from order line facts so the model held one row per line.",
      "Cleaned and shaped the data in Power Query, flagging failed records instead of dropping them.",
      "Built the DAX measure layer to resolve at line grain, which stopped the double counting.",
      "Compared revenue against margin by category, channel, region and customer group.",
      "Profiled seasonal demand across the three years and tested a short-horizon forecast against it.",
    ],
    workflow: [
      "13 source tables",
      "Profile + grain check",
      "Clean + flag exceptions",
      "Order-line model",
      "Margin + seasonality",
      "Forecast",
    ],
    findings: [
      "Revenue and margin move in opposite directions at the peaks. The highest-selling months carry the lowest gross margin, because the volume is bought with discount.",
      "The channel comparison changed once the grain was fixed. Mixing order and order-line facts had been overstating one channel against the other.",
      "Promotional revenue and base revenue behave differently enough that a single revenue trend hides the split between them.",
      "The seasonal shape repeats across all three years, which supports planning one to two quarters ahead. Past that horizon the pattern has not been tested, so I would not extend the forecast without re-running it.",
      "The repository publishes the model, the method and the 194,480-row scope. It does not publish final category margin percentages, so none are quoted here.",
    ],
    meaning: "The reporting was never short of numbers. It was short of a model that could hold revenue and profit in the same view without counting the same order twice. Fixing the grain changed what the numbers said, not how they looked.",
    recommendations: [
      "Read margin next to revenue on every category and channel view, never revenue alone.",
      "Track what share of revenue depends on discount, and watch that share at the peaks.",
      "Plan stock and campaigns against the repeating seasonal shape rather than last month's total.",
      "Judge online against physical on profit per order, not on sales volume.",
      "Treat the forecast as a planning input with a stated horizon, and re-test it each quarter.",
    ],
    output: "A retail reporting and forecasting model in Excel with a measure layer that resolves at order-line grain, covering revenue, profit, customers, categories, channels, regions and seasonality.",
    limitations: [
      "The data is synthetic and the business is fictional. Nothing here is a real trading result.",
      "The forecast assumes the historical seasonal shape holds. It has no view of price changes, competitor moves or supply disruption.",
      "Category-level margin percentages are not published in the repository, so this page does not state any.",
    ],
    judgement: "The grain mismatch was the whole problem. Nothing downstream could be trusted while order and order-line facts shared a model, so I fixed that before writing a single measure.",
  },
  {
    slug: "bloomcrest-revenue-intelligence",
    title: "Bloomcrest Revenue Intelligence & Revenue Operations",
    category: "Revenue Analytics · CRM · Automation",
    short: "Customer, sales, pipeline and payment data joined into one view, including a model that failed its test and was not shipped.",
    status: "Synthetic data · Fictional business",
    cover: "/project-covers/bloomcrest.svg",
    github: "https://github.com/oreoluwadaniel/bloomcrest-revenue-intelligence",
    scale: "18,000 customers · 360 wholesale deals · NGN 7.353B modelled revenue · Jul 2024 to Jul 2026",
    tools: [
      "PostgreSQL",
      "SQL",
      "Python",
      "pandas",
      "scikit-learn",
      "HubSpot",
      "Make.com",
    ],
    context: "Bloomcrest sells direct to consumers and through wholesale accounts. Each part of the business reported honestly and separately, which meant the direct-to-consumer number, the wholesale pipeline and the collections position never had to agree with each other in the same room.",
    problem: "Revenue questions cross systems. Whether the year is on track depends on the pipeline, which depends on collections, which depends on which customers are still buying. Answering that from four separate reports produces four defensible answers and no decision.",
    objective: "Put customer, order, pipeline and payment data on one PostgreSQL foundation, then answer the five questions a revenue lead actually gets asked, including the one about how much of the booked revenue has arrived.",
    questions: [
      "Are we on track against the revenue target?",
      "Which deals need attention this week?",
      "Which customers have gone quiet?",
      "How much of what we booked have we collected?",
      "Where is revenue leaking out of the process?",
    ],
    data: [
      "18,000 customers",
      "360 wholesale deals",
      "NGN 7.353B modelled revenue, split 43.6% direct-to-consumer and 56.4% wholesale",
      "July 2024 to July 2026",
      "Synthetic data with all foreign keys validated against the approved entity relationship diagram",
    ],
    work: [
      "Built the PostgreSQL foundation covering customers, orders, pipeline and payments.",
      "Joined CRM pipeline records to transactional revenue through a normalised company identity, with an exceptions table for the accounts that would not match.",
      "Wrote the SQL and Python analysis for revenue, acquisition, retention and collections.",
      "Added synchronisation logic between the operational systems and the analysis layer.",
      "Scored customer inactivity with RFM and sized the revenue attached to each segment.",
      "Trained and cross-validated a logistic regression lead-scoring model, then tested whether it was good enough to use.",
    ],
    workflow: [
      "Operational data",
      "PostgreSQL",
      "CRM identity match",
      "SQL + Python",
      "Revenue + retention",
      "Model evaluation",
    ],
    findings: [
      "Modelled revenue reached NGN 7.353B, split 43.6% direct-to-consumer and 56.4% wholesale.",
      "Closed deals produced a 48.6% win rate, and won deals averaged about 41.5 days from creation to close.",
      "Open pipeline stood at NGN 129.44M, of which NGN 55.09M was stage-weighted pipeline value. The unweighted figure is the one that flatters a forecast.",
      "6,129 of 18,000 customers had no successful order in the previous 90 days as at 20 July 2026.",
      "RFM put 3,884 customers in the At risk and Cannot lose segments, carrying about NGN 819M of historical successful-order revenue between them.",
      "The logistic regression lead-scoring model returned a five-fold ROC-AUC of 0.42, which is below random. It was not shipped as a scoring model, and the negative result is published rather than dropped.",
    ],
    meaning: "The value of joining the systems was not a prettier report. It was that the pipeline figure, the collections figure and the inactive customer count could finally contradict each other in public, which is when someone has to make a decision.",
    recommendations: [
      "Forecast on stage-weighted pipeline, and keep the unweighted number out of the commitment conversation.",
      "Work the 3,884 At risk and Cannot lose customers ahead of new acquisition, because the revenue is already proven.",
      "Track the 90-day inactivity count as a weekly number, since it moves before total revenue does.",
      "Report booked and collected revenue as two separate lines, permanently.",
      "Rebuild the lead-scoring model with different features, or drop the idea. Do not deploy an AUC of 0.42.",
    ],
    output: "A revenue intelligence system on PostgreSQL covering revenue, pipeline, acquisition, retention, collections and leakage, with an evaluated and rejected lead-scoring model documented alongside it.",
    limitations: [
      "The data is synthetic and the business is fictional. NGN 7.353B is a modelled figure, not company revenue.",
      "Customer behaviour is generated, so retention and inactivity patterns show that the method works rather than what real customers do.",
      "The lead-scoring result is a negative finding about this dataset and these features. It does not establish that lead scoring cannot work here.",
    ],
    judgement: "The lead-scoring experiment produced a cross-validated AUC of 0.42. It was not good enough to use, so I did not ship it, and I left the number on the page. A portfolio that only shows the models that worked is not showing you how the person works.",
  },
  {
    slug: "data-analytics-etl",
    title: "Data Analytics & ETL Portfolio",
    category: "Data Quality · ETL · Reporting",
    short: "Four cases on the part that happens before the dashboard, where 30.3% of CRM records failed and were routed rather than deleted.",
    status: "Synthetic data · Four linked cases",
    cover: "/project-covers/etl.svg",
    github: "https://github.com/oreoluwadaniel/data-analytics-etl-portfolio",
    scale: "5,130 CRM records · 1,001 employees · 3,400 SKUs · 75,000 sales transactions",
    tools: [
      "Excel",
      "Power Query",
      "Power Pivot",
      "DAX",
      "VBA",
      "SQL",
    ],
    context: "A duplicate customer inflates a pipeline. A missing manager distorts a workforce report. Negative stock hides an inventory problem. A future-dated sale makes a month look better than it was. All four survive the trip into a dashboard without complaint.",
    problem: "Cleaning data usually means making the errors disappear, which destroys the information that a record was wrong in the first place. That information is often the thing management most needs.",
    objective: "Build four reporting layers where failed records are routed to an exception queue and counted, so every published figure comes with a statement of what was excluded and why.",
    questions: [
      "Which records can be trusted in a management report?",
      "Which records need a person to look at them?",
      "Which missing fields are an operational problem rather than a data problem?",
      "Can the reporting layer explain its own exclusions?",
    ],
    data: [
      "CRM: 5,130 customer records",
      "HR: 1,001 employees across payroll, attendance, leave and performance",
      "Inventory: 3,400 SKUs",
      "Sales: 75,000 transactions across 13 branch exports",
      "Synthetic data, seeded with the defects real operational exports carry",
    ],
    work: [
      "Profiled each source and scored completeness before writing any transformation.",
      "Wrote explicit validation rules per case, then routed failures to exception tables.",
      "Combined payroll, attendance, leave and performance into one employee view while leaving missing fields visible.",
      "Applied 15 integrity checks to the inventory data before building the replenishment view.",
      "Standardised 13 branch sales exports into one model with validation ahead of the reporting layer.",
      "Reconciled every final count back to source and published the difference.",
    ],
    workflow: [
      "Raw exports",
      "Profile + score",
      "Validate",
      "Route exceptions",
      "Transform + model",
      "Reconcile",
    ],
    findings: [
      "1,555 of 5,130 CRM records, 30.3%, failed the defined quality checks and were routed for review rather than deleted.",
      "301 employees had no performance review recorded and 464 had no recorded manager. Both are management problems before they are data problems.",
      "The inventory analysis identified N6.49B of replenishment exposure across 3,400 SKUs. That is exposure to investigate, not money saved.",
      "74,598 of 75,000 source sales transactions were accepted into the reporting layer. The 402 rejected rows are accounted for, so management KPIs run from the cleaned layer and the gap is explainable.",
      "Payroll held 1,016 rows for 1,001 unique employees, which is the kind of quiet duplication that inflates a headcount report.",
    ],
    meaning: "The reason to keep exception records is that 464 employees without a manager is not noise to be swept up before the dashboard renders. It is a finding. Deleting it produces a cleaner report about a worse-understood business.",
    recommendations: [
      "Route failed records to an exception queue and report the count. Never silently delete.",
      "Treat missing owners, missing reviews and invalid stock as operational issues with an owner attached.",
      "Run integrity checks before the reporting layer, not after someone questions a number.",
      "Reconcile source and final counts on every refresh and publish the difference.",
      "State the exclusion rate on the report itself, so the reader knows what the number covers.",
    ],
    output: "Four reporting systems in Excel and Power Query covering CRM data quality, HR workforce reporting, inventory replenishment and multi-branch sales, each with validation rules, an exception route and a reconciliation.",
    limitations: [
      "The datasets are synthetic. The defects are realistic, the businesses are not real.",
      "The findings depend on the validation rules chosen. Different rules would route a different share of records.",
      "N6.49B of replenishment exposure is a measure of what is at risk, not a saving or a recovered amount.",
    ],
    judgement: "I kept the exception records visible. A blank manager field, an invalid stock record or a failed CRM check is information about the business, not a reason to quietly drop a row.",
  },
  {
    slug: "weatherintel",
    title: "WeatherIntel: Weather Analytics & Forecast Evaluation",
    category: "Forecasting · Data Engineering · Business Intelligence",
    short: "371,482 quality-checked station-days, and four forecasting methods put on the same test to see which one earns its place.",
    status: "NOAA public source data · Analytical project",
    cover: "/project-covers/weatherintel.svg",
    github: "https://github.com/oreoluwadaniel/weatherintel-global-weather-analytics",
    scale: "8 stations · 4 continents · 371,482 curated station-days · records back to 1763",
    tools: [
      "Python",
      "PostgreSQL",
      "SQL",
      "XGBoost",
      "SARIMA",
      "Power BI",
    ],
    context: "Agriculture, logistics, aviation, insurance and renewable energy all plan against historical weather. The archives those plans rest on contain missing observations, quality flags and stations whose coverage starts and stops without warning.",
    problem: "Two failures compound here. Observations that never passed a quality check get treated as fact, and a forecast that was never tested against a baseline gets treated as skill. Either one produces a confident plan built on nothing.",
    objective: "Keep raw observations and quality-checked observations apart, so it is always clear which is being used. Then benchmark four forecasting methods against each other on held-out data and publish all four errors.",
    questions: [
      "Which observations survive a defined quality check, and which do not?",
      "What do the historical patterns look like once the failures are removed?",
      "Does XGBoost beat persistence, linear regression and climatology?",
      "Is the margin large enough to justify the extra complexity?",
    ],
    data: [
      "NOAA GHCN-Daily observations",
      "8 stations across 4 continents",
      "371,482 curated station-days after quality checks",
      "History from 1763 through March 2018, varying by station",
      "Public source data, not synthetic",
    ],
    work: [
      "Parsed the NOAA station files and standardised fields across differing station formats.",
      "Preserved the source quality flags rather than discarding them during the load.",
      "Applied defined quality rules and kept the excluded observations traceable.",
      "Loaded the curated observations into a PostgreSQL star schema.",
      "Analysed historical temperature and precipitation patterns per station.",
      "Ran XGBoost, linear regression, persistence and climatology on the same held-out data and compared MAE and RMSE.",
    ],
    workflow: [
      "NOAA GHCN-Daily",
      "Parse + standardise",
      "Quality checks",
      "PostgreSQL star schema",
      "Model vs baseline",
      "Power BI",
    ],
    findings: [
      "XGBoost recorded the lowest error at 2.218°C MAE, against 2.331°C for persistence and 2.250°C for linear regression.",
      "On RMSE, XGBoost reached 2.804°C, against 2.973°C for persistence, 2.811°C for linear regression and 4.814°C for climatology.",
      "The margin over persistence is 0.113°C of MAE. That is a real improvement and a small one, and it has to be weighed against the cost of running and maintaining a gradient-boosted model.",
      "Linear regression sits within 0.032°C of XGBoost on MAE. For most planning uses it is the more defensible choice.",
      "371,482 station-days survived the published quality pipeline across 8 stations and 4 continents. Excluded observations stay traceable instead of disappearing.",
      "Station histories differ by more than two centuries, so any cross-station comparison has to carry coverage and history alongside the metric.",
    ],
    meaning: "The interesting result was not that the complex model won. It is that it won by 0.113°C over repeating yesterday's reading. That number is what a planning team needs in order to decide whether the model is worth owning.",
    recommendations: [
      "Keep raw and curated observations in separate tables, permanently.",
      "Record the quality rule that excluded each observation, so exclusions can be reviewed.",
      "Report every model against a naive baseline in the same table, at the same scale.",
      "Choose linear regression over XGBoost unless the 0.032°C difference matters for the decision at hand.",
      "Publish forecast error next to the forecast, so the reader can size the uncertainty.",
    ],
    output: "A weather data pipeline from raw NOAA files to a curated PostgreSQL warehouse, with a four-way forecast benchmark and a Power BI reporting layer.",
    limitations: [
      "Station coverage and history vary widely, so the eight stations are not a global sample.",
      "Forecast errors are for the tested stations and horizon. They do not transfer to other locations without re-testing.",
      "Weather responds to drivers outside these observations, and the models carry no view of them.",
    ],
    judgement: "I published the baselines even though they made the model look less impressive. A forecast only earns its place when it beats a simple benchmark on held-out data, and 0.113°C is the honest size of what was earned.",
  },
  {
    slug: "ab-testing-experimentation",
    title: "A/B Testing & Product Experimentation",
    category: "Experimentation · Product Analytics · Statistics",
    short: "Two product experiments where the ship decision, not the p-value, was the output. One of them came with a catch.",
    status: "Synthetic experiment data · Two linked cases",
    cover: "/project-covers/abtesting.svg",
    github: "https://github.com/oreoluwadaniel/ab-testing-case-studies",
    scale: "8,200 visitors over 42 days · 7,500 new mobile users",
    tools: [
      "Python",
      "pandas",
      "SciPy",
      "statsmodels",
      "Power BI",
      "Hypothesis Testing",
    ],
    context: "Two product teams each wanted to ship a change. A redesigned landing page, and a guided onboarding assistant in a mobile app. Both had a test behind them and both tests showed the treatment ahead.",
    problem: "A treatment can lead by chance, or lead by an amount too small to be worth the engineering. And measuring only the users who opted into a feature answers a different question from the one being asked, usually a flattering one.",
    objective: "Run both experiments to a decision. Validate the assignment, measure the effect at visitor and user level, quantify the uncertainty, check the segments, and state whether the evidence supports shipping.",
    questions: [
      "Was assignment actually random, and does the data support that?",
      "How large is the effect, and how large could it reasonably be?",
      "Does the result hold across devices and traffic sources?",
      "Are we measuring everyone assigned to treatment, or only the people who chose to use the feature?",
      "Is the improvement big enough to be worth shipping?",
    ],
    data: [
      "Landing page: 8,435 raw visit rows collapsing to 8,200 unique visitors, 4,120 control and 4,080 treatment",
      "Landing page test window: 18 May 2026 to 28 June 2026, 42 days",
      "Onboarding: 7,500 new mobile users, 3,714 control and 3,786 treatment",
      "Five app versions and two device platforms across the onboarding test",
      "Synthetic experiment data",
    ],
    work: [
      "Collapsed the landing page data from visits to unique visitors, so a visitor who converted on any visit counts once.",
      "Ran two-proportion z-tests on the binary conversion and retention outcomes.",
      "Used Mann-Whitney U tests for the skewed session-length and screen-count data.",
      "Reported 95% confidence intervals alongside every p-value.",
      "Applied a Bonferroni correction across segment comparisons to control false positives.",
      "Kept intent-to-treat as the primary analysis and treated adopter behaviour as supporting evidence only.",
      "Checked statistical power and minimum detectable effect before interpreting effect size.",
    ],
    workflow: [
      "Decision framed",
      "Design validated",
      "Visitor-level collapse",
      "Effect + interval",
      "Segment checks",
      "Ship decision",
    ],
    findings: [
      "Landing page conversion rose from 3.08% to 4.44%, a lift of 1.35 percentage points, or 43.9% relative. p = 0.0013, with a 95% confidence interval of +0.53pp to +2.18pp.",
      "The landing page result is supported by behaviour, not standing alone. Bounce fell from 65.5% to 58.8% and average time on page rose from 30.5 to 37.3 seconds.",
      "Collapsing 8,435 visit rows to 8,200 unique visitors mattered. Analysed at visit level with the first visit kept, the same data reads 2.94% against 4.04%, which is a materially different lift from a materially wrong unit of analysis.",
      "Onboarding D7 retention rose from 36.54% to 40.65%, a lift of 4.11 percentage points, or 11.3% relative. p = 0.0003, with a 95% confidence interval of +1.91pp to +6.31pp.",
      "Only 37.8% of treatment users opened the assistant. Among those who did, D7 retention was 50.5%. Among the treatment users who never opened it, retention was 34.6%, which sits below the control group's 36.54%.",
      "That last split is the finding worth acting on. The whole intent-to-treat lift is being produced by 37.8% of the group, so exposure is the constraint on the feature, not the feature.",
    ],
    meaning: "Both experiments support shipping. The onboarding one also hands the product team a better question than the one they asked: if 37.8% adoption produces a 4.11 point lift, the value sitting in the other 62.2% is larger than the value already captured.",
    recommendations: [
      "Ship the landing page redesign for the tested traffic and keep measuring conversion after release.",
      "Ship the onboarding assistant, then treat raising exposure above 37.8% as the next piece of work.",
      "Do not present the 50.5% adopter retention figure as the effect of the feature. Adopters chose to adopt, and that choice carries its own signal.",
      "Set the unit of analysis before the test starts. Visit level and visitor level give different answers from the same rows.",
      "Agree the minimum effect worth shipping before looking at the result, not after.",
    ],
    output: "Two completed experiment analyses in Python with design validation, effect sizes, confidence intervals, segment checks and a stated product decision, plus a Power BI view of the landing page test.",
    limitations: [
      "The experiment data is synthetic. The method is real, the users are not.",
      "The adopter comparison is observational and cannot establish that the assistant caused the higher retention among adopters.",
      "Both results apply to the tested populations and windows. Neither transfers to other traffic mixes without re-testing.",
      "Neither case study attaches a revenue figure to the lift, because the datasets carry no revenue per conversion.",
    ],
    judgement: "The onboarding test was a clean win and I did not report it as one. Treatment users who never opened the assistant retained at 34.6%, below control, so the honest read is that the effect is concentrated in a third of the group and the product question is exposure.",
  },
  {
    slug: "crestline-inventory-decision-support",
    title: "Crestline Inventory Decision Support",
    category: "Inventory · Scenario Modelling · Working Capital",
    short: "A purchase reported as a ₦9m saving that the model shows cost ₦8.4m once the stock had somewhere to sit.",
    status: "Synthetic data · Fictional business",
    cover: "/project-covers/crestline.svg",
    github: "https://github.com/oreoluwadaniel/crestline-inventory-decision-support",
    scale: "5 warehouses · 7 scenarios · ₦412.4M inventory value · data as at June 2026",
    tools: [
      "Excel",
      "Scenario Modelling",
      "EOQ",
      "Safety Stock",
      "Solver",
    ],
    context: "Crestline is a fictional five-warehouse distributor in Nigeria. Purchasing decisions there involve demand, supplier lead time, procurement cost, warehouse capacity and the naira, and they are made monthly against numbers that describe last month.",
    problem: "Buying too much ties up cash and fills warehouses. Buying too little loses sales. The judgement sits between those, and it is usually made on unit price, which is the one input that reliably misleads.",
    objective: "Build a decision model where a manager changes one operating assumption and watches inventory value, service level, cost and working capital move together, with every change measured against the base case.",
    questions: [
      "What happens to stock and cash if supplier lead times double?",
      "What if demand rises 30%, or falls 15%?",
      "What does a 12% procurement cost rise or a 20% FX uplift do to the position?",
      "Does a bulk discount still make sense once the stock has to be held?",
    ],
    data: [
      "Fictional five-warehouse Nigerian distributor",
      "Sales, purchase orders, transfers, returns, stock counts, storage and transport costs",
      "Executive position as at June 2026",
      "Seven scenarios: Base Case, Supplier Crisis, Demand Spike, Demand Decline, Cost Shock, Naira Slide, Bulk Deal",
      "Synthetic operating data",
    ],
    work: [
      "Built the inventory position from transaction-level data rather than from a summary export.",
      "Modelled EOQ and safety stock with an explicit service-level target and a documented carrying rate.",
      "Built a scenario engine driven by one dropdown, with every input visible on the sheet.",
      "Recalculated the executive view against the selected scenario and against the base case.",
      "Reviewed a real bulk purchase decision on total economic cost rather than on discount.",
      "Documented every assumption that is a consultant estimate rather than a client figure.",
    ],
    workflow: [
      "Operational data",
      "Inventory position",
      "Demand analysis",
      "Scenario engine",
      "Base case comparison",
      "Executive view",
    ],
    findings: [
      "A bulk purchase reported internally as a ₦9,000,000 saving was a net loss of ₦8,400,000. The 12% discount on a ₦75,000,000 order bought 8 months of stock, and holding cost over that period runs at 23% of value, or ₦17,400,000, against 12% saved.",
      "That figure still excludes the opportunity cost of the blocked warehouse space, so the true net position is worse than negative ₦8.4m.",
      "The carrying rate is 35%, built from 28% cost of capital, 1% insurance and 6% storage, spoilage and shrinkage. The prior estimate of 20% to 25% excluded cost of capital, which is what made the bulk deal look attractive in the first place.",
      "₦28,660,219 of inventory, 6.9% of the ₦412,412,369 total, sits in six months or more of cover. That is the largest single lever against the 20% reduction target.",
      "OTIF stands at 70.5% on a trailing three-month basis against a 90% threshold, while fill rate is 97.5% against a 95% target. The two service measures disagree, and the OTIF gap is the one that reaches customers.",
      "Lagos Main runs at 77% warehouse utilisation, the highest in the network, which caps how much more stock any scenario can absorb there.",
      "Inventory turnover is 12.38 with days inventory outstanding at 29.48, and inventory value sits 1.2% above target after rising 6.6% month on month.",
    ],
    meaning: "The bulk deal is the case that earns the model. The saving was real, it was reported accurately, and it was still the wrong decision, because the number that made it wrong was never in the room. A discount is only a saving if the business is not paying to store the discount.",
    recommendations: [
      "Route every bulk purchase through total economic cost before approval, not through discount percentage.",
      "Get the 35% carrying rate signed off by finance, because it changes which purchases clear the bar.",
      "Attack the ₦28.66M sitting in six-plus months of cover first. It is the largest recoverable position.",
      "Investigate the six suppliers behind the late deliveries. OTIF at 70.5% is 19.5 points below threshold.",
      "Rebalance stock away from Lagos Main at 77% utilisation before it constrains the next demand scenario.",
      "Re-run the scenario set before any commitment large enough to matter, and compare against base case rather than against last month.",
    ],
    output: "An Excel decision-support model with a seven-scenario engine, EOQ and safety-stock calculations, an executive dashboard that repaints against the selected scenario, and a documented assumption register.",
    limitations: [
      "The data is synthetic and the distributor is fictional.",
      "Scenario outputs are estimates under the stated assumptions, not forecasts. The model separates actual historical values from scenario outputs for exactly that reason.",
      "Several inputs are flagged in the workbook as consultant estimates awaiting client confirmation, including the stockout goodwill uplift, the warehouse space cap and the placeholder storage and transport rates.",
      "The forecast uses a manually set annual seasonality because only two historical cycles exist, which is too few for automatic detection to work.",
    ],
    judgement: "I recalculated the carrying rate before anything else. The prior 20% to 25% estimate left out cost of capital, and at 28% cost of capital that omission is the entire difference between a ₦9m saving and an ₦8.4m loss. Fixing the assumption mattered more than any scenario I could run on top of it.",
  },
  {
    slug: "credit-risk-banking-portfolio",
    title: "Credit Risk & Banking Analytics Portfolio",
    category: "Credit Risk · Banking · SQL",
    short: "Five lending-risk case studies, including two where the tool the bank was relying on turned out to have no signal in it.",
    status: "Synthetic data · Five linked cases",
    cover: "/project-covers/creditrisk.svg",
    github: "https://github.com/oreoluwadaniel/credit-risk-banking-portfolio",
    scale: "1,000 loans · 10,000 monthly panel rows · 3,000 bank loans · 3,000 transactions",
    tools: [
      "SQL",
      "SQL Server",
      "Window Functions",
      "Python",
      "pandas",
      "Statistical Testing",
    ],
    context: "Credit risk does not start at default. It starts when a borrower slips a payment, and it becomes expensive somewhere between there and the write-off. Five case studies follow a synthetic lending book across that path, from early deterioration to fraud screening.",
    problem: "Risk teams work from two things they rarely test: an assigned risk band, and an anomaly score. Both look like tools. Neither is useful unless it separates the outcome it claims to separate, and that is a question with an answer.",
    objective: "Measure stage migration and expected loss, locate the non-performing exposure, track delinquency movement month to month, and then test whether the risk band and the fraud score actually do their jobs.",
    questions: [
      "Which loans are moving into higher-risk stages, and what does that cost?",
      "Where is non-performing exposure concentrated?",
      "How fast are loans rolling between delinquency buckets, and how many cure?",
      "Does the assigned risk band separate defaulters from performers?",
      "Does the fraud score rank suspicious transactions better than chance?",
    ],
    data: [
      "IFRS 9 case: 1,000 loans, 10,000 monthly panel rows across 25 month-ends from Jan 2023 to Jan 2025",
      "Total loan exposure of approximately 10.0M currency units across the staged book, spread over five countries",
      "Default case: 3,000 bank loans across Auto, Business, Personal and Mortgage in five countries",
      "Fraud case: 3,000 transactions with flags and anomaly scores",
      "Shared synthetic loan portfolio",
    ],
    work: [
      "Classified loans into IFRS 9 stages from days past due and measured expected loss as exposure times PD times LGD.",
      "Measured NPL concentration by country and credit tier.",
      "Built the roll-rate matrix from the monthly panel to track movement between delinquency buckets.",
      "Tested default rates against risk band, credit score, loan type and country with chi-square and t-tests.",
      "Checked whether ranking transactions by fraud score concentrates the flagged cases.",
      "Profiled the join keys before running any of it.",
    ],
    workflow: [
      "Loan panel",
      "Stage classification",
      "Expected loss",
      "Roll rates",
      "Segment testing",
      "Fraud ranking",
    ],
    findings: [
      "The book splits 87.0% Stage 1, 9.6% Stage 2 and 3.6% Stage 3 by loan count, with exposure following almost the same shape at 87% / 9% / 4%. Total expected loss is approximately 846,000, or 8.46% of exposure.",
      "10.6% of loans carry an NPL flag, and the days-past-due profile runs 590 current, 148 in 1 to 30, 115 in 31 to 60, 82 in 61 to 90 and 65 at 90 plus.",
      "The roll-rate matrix shows 268 of 408 loan-months at 90 plus days past due returning to current, a cure rate of about 66%. On a synthetic book that is a property of the generator, and on a real book it would be the first number to challenge.",
      "The assigned risk band does not separate defaults. High risk defaults at 11.4%, medium at 11.3% and low at 10.2%, and the chi-square test returns p = 0.74. As it stands the band cannot be used to prioritise collections or capital.",
      "Credit score does not separate defaults either. Defaulters average 587.5 against 572.9 for performers, in the wrong direction, at p = 0.21.",
      "Country does separate, at p = 0.004. Default rates run from 8.0% in Canada and 8.3% in Nigeria to 12.8% in the USA and 13.4% in the UAE.",
      "The fraud score has no ranking power. Taking the top 300 transactions by score captures 13 flagged cases against the 13.4 expected from a random draw of the same size, on a 4.5% base rate. Ranking by that score is the same as not ranking.",
      "credit_scores.csv contains 1,070 duplicate customer_id rows. Joining it without deduplicating inflates a 3,000-row loan book to 3,028 rows and quietly changes every rate calculated from it.",
    ],
    meaning: "Three of the five cases produced a working measurement. The other two produced a negative result, which is more useful: a risk band that does not separate risk and a fraud score that does not rank fraud are both worse than having neither, because a team will act on them.",
    recommendations: [
      "Stop using the risk band for prioritisation until it demonstrates separation on outcomes.",
      "Rebuild the fraud score, or replace it with a rule set. Ranking by a score with no lift wastes the investigation capacity it was meant to focus.",
      "Deduplicate credit_scores on customer_id before any join, and check row counts before and after.",
      "Use country as a segmentation input, since it is the one attribute here that separates default at conventional significance.",
      "Watch the Stage 1 to Stage 2 migration monthly. It moves before the NPL ratio does.",
      "Challenge the 66% cure rate against a real book before using it in any provisioning assumption.",
    ],
    output: "Five SQL case studies covering IFRS 9 staging and expected loss, NPL monitoring, roll-rate migration, default risk analysis and transaction fraud screening, with statistical tests on the segments that claim to carry signal.",
    limitations: [
      "The portfolio is synthetic. Default rates, cure rates and score distributions are properties of the data generator, not of a lending market.",
      "The negative results say the risk band and fraud score carry no signal in this dataset. They do not establish that such scores are useless in general.",
      "1,062 of 3,000 loans have no matching credit score after deduplication, so the credit-score test runs on the subset that does.",
      "Fraud flags here are screening outputs. None of them is a confirmed fraud.",
    ],
    judgement: "I tested the risk band instead of reporting on it. A chi-square of p = 0.74 across High, Medium and Low means the bank's own segmentation is not telling it anything about default, and that is a finding worth more than another NPL chart built on top of the same band.",
  },
  {
    slug: "stock-risk-monitoring",
    title: "Stock Performance, Risk & Forecast Monitoring",
    category: "Financial Analytics · Risk · Forecasting",
    short: "21,380 daily prices used to test whether an ARIMA forecast beats repeating yesterday's close. It did not.",
    status: "Yahoo Finance market data · Analytical project",
    cover: "/project-covers/stock.svg",
    github: "https://github.com/oreoluwadaniel/stock-performance-risk-monitoring",
    scale: "10 US large-cap stocks · 21,380 daily price records · 2 Jan 2018 to 7 Jul 2026",
    tools: [
      "Python",
      "PostgreSQL",
      "SQL",
      "ARIMA",
      "Power BI",
    ],
    context: "A price chart answers what happened. It does not answer where the downside sits, which holdings are really the same bet under two names, or whether a forecast adds anything to a monitoring process.",
    problem: "Ten holdings can look diversified and behave like four. And a forecast scored on the data it was fitted to will almost always look good, which is why in-sample fit is the most flattering test available.",
    objective: "Build a monitoring layer covering return, downside risk, correlation and concentration, then test ARIMA with walk-forward evaluation against a naive last-value baseline and report whichever wins.",
    questions: [
      "Which holdings contributed return, and at what drawdown?",
      "Where is downside risk concentrated?",
      "Which holdings move together closely enough to count as one exposure?",
      "Does ARIMA beat repeating the last price?",
    ],
    data: [
      "10 US large-cap stocks",
      "21,380 daily price records",
      "2 January 2018 to 7 July 2026",
      "Yahoo Finance historical adjusted prices",
      "Real market data, not synthetic",
    ],
    work: [
      "Validated the price series for gaps, splits and adjustment errors before any analysis.",
      "Engineered returns, rolling volatility and drawdown features.",
      "Stored the structured series in PostgreSQL.",
      "Measured cumulative performance, maximum drawdown, volatility and pairwise correlation.",
      "Ran ARIMA forecasts under walk-forward evaluation over a 30-session horizon.",
      "Scored ARIMA and a naive last-value baseline on the same held-out windows.",
    ],
    workflow: [
      "Price data",
      "Validation",
      "Feature engineering",
      "Risk + correlation",
      "Walk-forward test",
      "Power BI",
    ],
    findings: [
      "Cumulative adjusted-price performance ranged from +94.2% for CVX to +675.5% for AAPL over the period.",
      "Maximum drawdown ranged from -23.8% for PG to -61.4% for UNH. Return and drawdown rank the holdings differently, so return alone says nothing about risk.",
      "XOM and CVX returned a 0.843 correlation, and AAPL and MSFT returned 0.669. Holding XOM alongside CVX is close to holding one energy position twice.",
      "All ten securities showed latest 30-day annualised volatility above their own historical median in the published snapshot.",
      "Average ARIMA MAPE was 5.732% against 5.716% for the naive baseline, giving average skill of -0.33%. The model was beaten by repeating the last price.",
    ],
    meaning: "Two results here are worth more than a return ranking. The correlation clusters mean the holding count overstates the diversification, and the forecast test means the complexity bought nothing. Both are the kind of finding that only appears if you run the test that can fail.",
    recommendations: [
      "Monitor correlation clusters, not the number of holdings.",
      "Read drawdown next to return on every position.",
      "Score every forecast against a naive baseline before it enters a monitoring process.",
      "Do not use this ARIMA configuration for forecasting. It did not clear the baseline.",
      "Re-test the volatility signal on a later snapshot before treating it as a regime change.",
    ],
    output: "A portfolio monitoring system covering performance, downside risk, correlation and concentration, with a walk-forward forecast evaluation that returned a negative result.",
    limitations: [
      "Historical performance does not carry forward, and none of this is investment advice.",
      "The result is monitoring and evaluation, not a trading recommendation.",
      "Ten large-cap US securities are not a portfolio, and the correlation structure would change with a wider or different universe.",
    ],
    judgement: "I did not score the forecast on the data it was fitted to. Walk-forward testing is slower and it is the only version that tells you whether the model adds anything, which here it did not.",
  },
  {
    slug: "kavora-crm-migration",
    title: "Kavora CRM Migration & Data Governance",
    category: "CRM Data · Data Quality · Migration",
    short: "Seven legacy exports turned into CRM-ready records, with the unresolved gap written down instead of hidden.",
    status: "Synthetic data · Fictional business",
    cover: "/project-covers/kavora.svg",
    github: "https://github.com/oreoluwadaniel/kavora-crm-migration-data-governance",
    scale: "7 legacy exports · 4,755 raw rows · 389 companies · 964 contacts · 380 deals",
    tools: [
      "Python",
      "Pandas",
      "Excel",
      "Power Query",
      "Record Matching",
      "Deduplication",
    ],
    context: "Kavora's customer history sat in seven legacy CSV exports written by different systems at different times. Field names disagreed, dates were formatted four ways, company names varied by punctuation, and the same deal appeared under 30 different stage labels.",
    problem: "A direct import would have carried all of that into the new CRM. Duplicate companies, contacts attached to the wrong parent, and pipeline reporting that nobody trusts within a month. A CRM loses its users the first time the numbers in it are visibly wrong.",
    objective: "Build a migration that decides what is safe to merge automatically, what a human has to look at, and what should not move at all. Then reconcile the output so the counts can be defended.",
    questions: [
      "Which records can be merged without a person looking at them?",
      "Where should the matching logic stop being trusted?",
      "How do companies and contacts get matched when the keys disagree?",
      "Can the final import files be reconciled back to the seven sources?",
    ],
    data: [
      "7 legacy CSV exports",
      "4,755 raw rows",
      "30 raw deal stages mapping to 7 standard stages",
      "3,363 unique normalised source email identities",
      "Synthetic data, structured to reproduce real legacy CRM defects",
    ],
    work: [
      "Profiled all seven exports and documented what each field actually contained rather than what its name claimed.",
      "Standardised names, dates, addresses and deal stages so records could be compared on the same basis.",
      "Matched companies and contacts, then set a confidence threshold below which nothing merges automatically.",
      "Routed everything under the threshold to an exceptions file for human review.",
      "Produced Company, Contact and Deal files shaped for import.",
      "Reconciled the final counts against the sources and recorded what did not reconcile.",
    ],
    workflow: [
      "7 legacy exports",
      "Profile + standardise",
      "Match + score",
      "Merge or hold",
      "Reconcile",
      "CRM-ready files",
    ],
    findings: [
      "4,755 raw rows produced 389 companies, 964 contacts and 380 deals.",
      "43 of the 389 companies share an email domain with another company, which is why domain alone cannot be the company key. The import assigns a stable Company ID instead.",
      "964 imported contacts sit against 3,363 unique source email identities, and that gap is not yet explained. It is recorded as the largest open item in the package, not written off.",
      "Closing the gap needs a rejection and quarantine log holding source file, source row, issue and final disposition. That log does not exist yet.",
      "An earlier version of the documentation claimed 6 source workbooks and 34 raw stages. Both were wrong once checked against the files. The corrected figures are 7 exports and 30 raw stages.",
    ],
    meaning: "A migration is a data quality job wearing an import job's clothes. The useful output is not a file that loads without errors. It is a file that loads without errors plus a written account of everything that did not make it and why.",
    recommendations: [
      "Profile every source file before agreeing a migration date.",
      "Set the matching threshold before running the match, not after seeing the results.",
      "Give uncertain records to a person rather than to an algorithm's best guess.",
      "Build the rejection and quarantine log before the import, because it cannot be reconstructed afterwards.",
      "Reconcile source and destination counts and publish the difference, including the part still unexplained.",
    ],
    output: "Company, Contact and Deal import files with matching rules, an exceptions route, a reconciliation and a written list of open items.",
    limitations: [
      "This is not a completed production import and there is no client deployment behind it.",
      "There is no claim of zero duplicates and no claim of full reconciliation of all 4,755 source rows.",
      "The 964 to 3,363 contact gap is documented but not yet resolved.",
      "Matching quality is bounded by the fields the legacy exports happened to carry.",
    ],
    judgement: "The hard part was choosing where to stop trusting the matching logic. Everything below the confidence threshold became an exception for human review on purpose, and I published the contact gap rather than rounding it away.",
  },
  {
    slug: "saas-revenue-product-billing",
    title: "SaaS Revenue, Product & Billing Analytics",
    category: "SaaS Analytics · Retention · Collections",
    short: "One customer foundation read three ways, on a book where past-due subscriptions almost equal active ones.",
    status: "Synthetic data · Three linked cases",
    cover: "/project-covers/saas.svg",
    github: "https://github.com/oreoluwadaniel/saas-analytics-portfolio",
    scale: "5,000 customers · 5,000 subscriptions · 6,000 invoices · 6,000 payments · 7,000 usage events",
    tools: [
      "SQL Server",
      "T-SQL",
      "Cohort Analysis",
      "Revenue Analytics",
    ],
    context: "Finance, Product, Customer Success and Revenue Operations all describe the same subscription business and rarely from the same table. Finance sees invoices, Product sees usage, Customer Success sees status, and the customer sits underneath all three.",
    problem: "Recurring revenue can grow while engagement weakens and cash collection slips, and each team can be reporting accurately while missing it. The failure is structural, not analytical.",
    objective: "Put customers, subscriptions, usage, invoices and payments on one foundation, then build three analytical views on top of it so the same customer story reads consistently across the four teams.",
    questions: [
      "Is recurring revenue growing, and what is churn taking out of it?",
      "Which customers are disengaging while still paying?",
      "What has been billed and not collected?",
      "Which accounts should collections work first?",
      "Are payment problems arriving before churn does?",
    ],
    data: [
      "5,000 customers and 5,000 subscriptions",
      "5 pricing plans, $29.99 to $199.99 per month",
      "6,000 invoices and 6,000 payments",
      "7,000 product usage events across 5 tracked features",
      "Synthetic SaaS dataset, approximately 29,000 records total",
    ],
    work: [
      "Built one customer foundation joining subscriptions, plans, usage, invoices and payments.",
      "Resolved current subscription state per customer before any measurement, since a customer can hold several.",
      "Measured MRR, churn, customer lifetime value and revenue movement.",
      "Measured engagement, feature adoption and disengagement signals against subscription status.",
      "Measured billed against collected revenue, invoice aging, failed payments and partial payments.",
      "Handled null payment records explicitly, so accounts with no payment at all stay in the collections view instead of dropping out of the join.",
    ],
    workflow: [
      "Customers",
      "Subscriptions + plans",
      "Usage + invoices + payments",
      "Validation",
      "Three analytical views",
      "Prioritised actions",
    ],
    findings: [
      "Subscription status splits 1,776 active, 1,772 past due and 1,452 cancelled. Past due almost equals active, at 35.4% of the book against 35.5%.",
      "1,471 of 6,000 invoices are unpaid, 24.5% of everything billed.",
      "1,224 of 6,000 payment attempts failed, 20.4%. Failed payment is a churn signal arriving through the finance system rather than the product one.",
      "The past-due population is the operating finding. A book where a third of subscriptions are past due is a collections problem being reported as a revenue number.",
      "Handling nulls correctly changes the collections list. Accounts with no payment record at all are the ones an inner join silently removes, and they are the accounts that most need chasing.",
      "The repository publishes the SQL and the data dictionary for all three cases. It does not publish final MRR, churn or leakage totals, so none are quoted here.",
    ],
    meaning: "The value of one shared foundation is that it forces the three views to agree on who the customer is. A customer flagged as disengaged in the product view and past due in the billing view is the same account, and only a shared foundation makes that visible before the renewal date.",
    recommendations: [
      "Treat the 1,772 past-due subscriptions as a retention list, not a receivables list.",
      "Route failed payments to Customer Success as well as to Finance, since a 20.4% failure rate is a churn signal.",
      "Read engagement next to payment status on the same customer record before any renewal conversation.",
      "Keep accounts with no payment record in the collections view by using outer joins deliberately.",
      "Publish MRR, churn and uncollected revenue totals from the existing SQL, so the case studies carry headline figures.",
    ],
    output: "Three T-SQL case studies on one customer foundation, covering MRR and churn, product usage and customer health, and billing, collections and revenue leakage.",
    limitations: [
      "The dataset is synthetic. The status and payment distributions were designed to carry realistic failure patterns.",
      "The repository publishes SQL and documentation without the generated dataset, so the queries are readable but not runnable as shipped.",
      "Final revenue, churn and leakage totals are not published in the repository, and this page does not invent them.",
      "Usage covers 5 features and 7,000 events, which supports engagement comparison rather than detailed product analytics.",
    ],
    judgement: "The null handling in the billing case is the part I would defend hardest. An inner join between invoices and payments produces a clean collections report that has quietly dropped every account that has never paid anything, which is the exact population the report exists to find.",
  },
  {
    slug: "insurance-risk-pricing",
    title: "Insurance Risk, Pricing & Profitability Analytics",
    category: "Insurance · Underwriting · Claims",
    short: "3,000 policies and 3,000 claims, and a join that returns exactly the right number of rows while being completely wrong.",
    status: "Synthetic data · Four linked cases",
    cover: "/project-covers/insurance.svg",
    github: "https://github.com/oreoluwadaniel/insurance-risk-pricing-analytics",
    scale: "3,000 policies · 3,000 claims · 4 product lines · 2018 to 2024",
    tools: [
      "SQL",
      "Relational Modelling",
      "Portfolio Analysis",
      "Segmentation",
    ],
    context: "An insurance book can grow while it gets worse. Premium arrives monthly and claims arrive later, so a portfolio that is underpriced looks healthy for exactly as long as it takes the claims to land.",
    problem: "Two traps sit in the joins before any analysis starts. Claims are at a different grain from policies, so joining them raw multiplies premium. And the supporting tables have duplicate keys that happen to cancel out against missing ones, so the row count after the join looks correct while the population has quietly changed.",
    objective: "Profile every join key first. Then measure loss ratio by product line, test whether premium tracks the risk that underwriting assessed, check whether the fraud signals rank fraud, and see whether claims cost moves with the wider economy.",
    questions: [
      "Which product lines are consuming the most premium in claims?",
      "Does premium reflect the risk accepted at underwriting?",
      "Do the fraud signals rank claims better than chance?",
      "Is claims cost moving with inflation, unemployment and interest rates?",
    ],
    data: [
      "3,000 policies across Auto, Property, Life and Health",
      "3,000 claims spread across 1,861 distinct policies",
      "3,000 underwriting rows covering 1,901 distinct policies",
      "3,000 fraud signal rows covering 1,879 distinct claims",
      "Claims dated 2018 to 2024, with daily economic observations brought to annual grain",
      "Simulated insurance portfolio",
    ],
    work: [
      "Profiled every join key for duplicates and coverage before writing a single measure.",
      "Aggregated claims to one row per policy before joining back to policy exposure.",
      "Measured loss ratio as settled claims over premium, by product line and by customer.",
      "Tested the underwriting risk score against the premium charged and against subsequent claims.",
      "Tested whether ranking by anomaly score or network flag concentrates the flagged claims.",
      "Brought claims and economic data to the same annual grain before comparing them.",
    ],
    workflow: [
      "Policies + claims",
      "Key profiling",
      "Aggregate to policy",
      "Loss ratio + pricing",
      "Fraud triage test",
      "Economic context",
    ],
    findings: [
      "Joining underwriting.csv to policies raw returns exactly 3,000 rows, so a row-count check passes. It should not. Only 1,901 of those 3,000 rows carry distinct policy IDs, so 1,099 policies drop out of the analysis and 1,099 duplicates take their place. fraud_signals.csv has the same shape, with 1,879 distinct claim IDs across 3,000 rows.",
      "1,861 of 3,000 policies carry at least one claim, 62.0% of the book. The remaining 1,139 have none, and 1,827 policies settled more than they were charged.",
      "The premium and settlement scales in this simulated book are not calibrated to each other. Settlements average about 15 times premium, so absolute loss ratios here carry no real-world meaning and are used only to rank one product line against another.",
      "On that relative basis the order is Health, Life, Property, Auto, from weakest to strongest. The spread is narrow, which is itself a finding: nothing in this portfolio points at a single problem product.",
      "Premium does not track the risk underwriting assessed. Across the 1,901 policies that have an underwriting record, the correlation between risk score and premium charged is -0.037. Whatever set the price, it was not the risk assessment.",
      "299 of 3,000 claims carry a fraud flag, 9.97% of the book, attached to about 11.44M of settlement value.",
      "Neither fraud signal ranks fraud. Deduplicated to the 1,879 claims that carry a signal row, the base rate is 9.26%. The top 300 by anomaly score contain 32 flagged cases against the 27.8 a random draw returns, and network-flagged claims run 8.97% against 9.54% for the unflagged, so the flag points slightly the wrong way.",
      "Claims volume is flat across 2018 to 2024, running between 418 and 445 a year with no trend, which is the honest reason the economic comparison has no claims-cost movement to explain.",
    ],
    meaning: "The join controls are the load-bearing part of this project. One join multiplies premium across the 1,861 policies that carry claims. The other silently swaps 1,099 policies for 1,099 duplicates while keeping the row count intact. Both produce a report that reconciles on volume and is wrong on every rate in it.",
    recommendations: [
      "Aggregate claims to policy grain before joining, as a standing rule rather than a step in one query.",
      "Check distinct key counts, not row counts, on every join. The row count does not warn you here.",
      "Stop using the anomaly score and the network flag for triage. Neither lifts above the base rate, so a queue built on them is a random sample with a ranking printed on it.",
      "Investigate why premium does not track the underwriting risk score. That is the pricing question this book actually raises.",
      "Do not quote absolute loss ratios from this dataset. Use it for relative product-line ranking and say so on the page.",
      "Re-run the economic comparison against a book with a real claims-cost trend before drawing any pricing conclusion from it.",
    ],
    output: "Four SQL case studies covering claims performance and loss ratio, underwriting and premium adequacy, fraud triage and macroeconomic claims context, built on a shared foundation with explicit grain and key controls.",
    limitations: [
      "The portfolio is simulated and the premium-to-settlement relationship is not economically calibrated, which is stated wherever a ratio appears.",
      "The analysis supports underwriting and portfolio review. It does not replace actuarial pricing or regulatory review.",
      "Fraud outputs are screening signals for human investigation, not findings of fraud.",
      "The pricing and fraud results are negative findings about this dataset. They do not establish that risk-based pricing or anomaly scoring fail in general.",
      "The macroeconomic comparison would establish whether claims cost and economic conditions move together. It could not establish causation even with a trend to work on.",
    ],
    judgement: "I profiled the join keys before I wrote a single loss ratio, and that is the only reason this analysis is not wrong. The underwriting join returns exactly 3,000 rows against a 3,000-row policy table. Everything about that looks correct, and 1,099 policies are missing from it.",
  },
  {
    slug: "stratavax-logistics",
    title: "Stratavax Logistics Analytics",
    category: "Logistics · Operations Analytics · SQL",
    short: "Two SQL analyses on delivery delay and delivery economics, both of which produced believable answers that turned out to be wrong.",
    status: "Synthetic data · Fictional business",
    cover: "/project-covers/stratavax.svg",
    github: "https://github.com/oreoluwadaniel/stratavax-logistics-analytics",
    scale: "6 related tables · 3,000 rows per table · 18,000 rows total",
    tools: [
      "SQL",
      "Relational Modelling",
      "Operations Analysis",
      "Cost Analysis",
    ],
    context: "Stratavax is a fictional delivery company running orders, deliveries, drivers, vehicles, customers and payments across six related tables. Two questions sat on top of it: why deliveries run late, and where the cost of running them eats the margin.",
    problem: "Both questions are easy to answer badly. A SQL query that executes cleanly and returns plausible numbers is the most dangerous output in analytics, because nothing about it announces that the join was wrong.",
    objective: "Answer the delay question and the profitability question separately, then check both against the source records before either goes near a decision.",
    questions: [
      "Why are deliveries late, and which locations and drivers carry the risk?",
      "Which routes cost more to run than they return?",
      "Where does fuel absorb the delivery margin?",
      "Do the query outputs actually agree with the underlying records?",
    ],
    data: [
      "6 related tables: orders, deliveries, drivers, vehicles, customers, payments",
      "3,000 rows per table",
      "Synthetic data, structured to reproduce real operational defects",
    ],
    work: [
      "Analysed delivery records for delay patterns by location, driver and route.",
      "Built a per-delivery risk score for SLA intervention.",
      "Analysed delivery revenue against operating cost, including fuel.",
      "Checked every material query output against source records instead of accepting it.",
      "Rebuilt two analyses after the checks failed.",
    ],
    workflow: [
      "6 operational tables",
      "SQL analysis",
      "Check against source",
      "Rebuild what failed",
      "Risk + profitability",
    ],
    findings: [
      "749 of 3,000 orders were flagged as delayed, just under 25%.",
      "The delay analysis found delivery dates preceding order dates across a large share of records, so every duration KPI was rebuilt from delivery_time_hours rather than from the date difference.",
      "The name Sadiq Ahmed appears 549 times across distinct driver IDs. Grouping driver performance by name produced a confident and meaningless result, so the analysis was regrouped by driver_id.",
      "The profitability analysis had payment fan-out, with multiple payment rows per order multiplying revenue on the join. Payments were aggregated to one row per order before joining, and profitability was scoped to delivered orders.",
      "After correction, revenue, cost and profit reconcile against source, and the risk and loss-making delivery outputs run on the corrected logic.",
      "Delay risk and cost pressure sit on different routes. The slowest routes are not the least profitable ones.",
    ],
    meaning: "Three separate analyses returned answers that looked right and were not. That is the actual content of this project. The reconciliation step is the difference between an operations report and an operations report that survives contact with the person who runs the depot.",
    recommendations: [
      "Reconcile query output against source records before any operational decision, especially when the output looks reasonable.",
      "Group by keys, never by names. 549 rows under one driver name is what that mistake costs.",
      "Check for fan-out on every one-to-many join before trusting a revenue or cost total.",
      "Use the per-delivery risk score to intervene before the SLA breach rather than reporting it afterwards.",
      "Read route profitability next to route delay, because they point at different routes.",
    ],
    output: "Two reconciled SQL analyses covering delivery delay risk, SLA intervention, route profitability and fuel cost, with the corrections documented.",
    limitations: [
      "The data is synthetic and the business is fictional.",
      "Risk scores rank deliveries by likelihood of delay. They are not predictions and carry no measured accuracy.",
      "There is no deployment and no measured operational outcome behind this.",
    ],
    judgement: "Two SQL outputs looked believable and did not reconcile to source. I treated that as a failed analysis until the discrepancy was explained, which is how the driver-name and payment fan-out problems surfaced at all.",
  },
  {
    slug: "brightwatt-operations",
    title: "Brightwatt Operations Automation",
    category: "Operations · Process Design · CRM Operations",
    short: "An 18-person solar installer whose real problem was sequencing, not software.",
    status: "Synthetic data · Fictional business · Design case study",
    cover: "/project-covers/brightwatt.svg",
    github: "https://github.com/oreoluwadaniel/Brightwatt-Operations-Automation",
    scale: "Fictional 18-person solar installation company, Lagos",
    tools: [
      "Process Design",
      "Workflow Automation",
      "CRM Operations",
      "Data Modelling",
    ],
    context: "Brightwatt is a fictional 18-person solar installation company in Lagos. Customers, orders, stock, payments, appointments, technicians and follow-ups each live somewhere different, and the connections between them live in whoever happens to remember.",
    problem: "When the stages are disconnected, work stalls at the handoffs rather than inside the stages. An installation gets scheduled before anyone checks stock. A balance goes unchased because no one owns it. Nothing looks broken until a customer asks.",
    objective: "Map the operating process, attach an owner to every stage, connect the stages so the record moves with the work, and surface unfinished work to a manager without anyone having to go looking for it.",
    questions: [
      "Is the customer record complete enough to act on?",
      "What did the customer order, and is the stock there?",
      "Who owns this installation right now?",
      "How much has the customer paid, and what is outstanding?",
      "What work is open, and how long has it been open?",
    ],
    data: [
      "Fictional 18-person solar installation company in Lagos",
      "Customer, order, inventory, payment, appointment, technician and task records",
      "Synthetic operating records",
      "Design case study, not a deployment",
    ],
    work: [
      "Mapped the current operating process stage by stage and located where work stalls.",
      "Designed structured customer intake with validation and a duplicate check ahead of record creation.",
      "Connected orders to inventory availability so stock is checked before a date is committed.",
      "Linked payments to both the customer and the order record.",
      "Attached technician ownership to appointments and field work.",
      "Built rule-based follow-up so open work raises a task instead of waiting to be remembered.",
    ],
    workflow: [
      "Customer intake",
      "Order",
      "Inventory check",
      "Payment",
      "Appointment",
      "Technician",
      "Follow-up",
    ],
    findings: [
      "The stall points cluster at handoffs between people, not inside the individual stages.",
      "Scheduling before checking stock is a sequencing error. It survives any software purchase, which is why the handoff rule had to be fixed before any tooling decision.",
      "A stage without a named owner stays invisible until a customer or a manager asks about it.",
      "Rule-based follow-up catches open work without depending on someone remembering to check.",
      "The repository documents the operating design. It does not claim measured time savings, recovered payments or reduced installation delays, because none were measured.",
    ],
    meaning: "The defensible result here is process visibility. A manager can follow one job from enquiry through order, stock, payment, appointment, technician and follow-up, and see where it is sitting. That is the whole claim, and it is stated as the whole claim.",
    recommendations: [
      "Name an owner for every stage before automating any of it.",
      "Check stock before committing an installation date, as a rule rather than as a habit.",
      "Connect payment status to both the customer and the order, so neither view is missing it.",
      "Raise follow-up tasks from rules, not from memory.",
      "Measure handoff time and open-task age first, so a later automation has a before to compare against.",
    ],
    output: "A connected operating design for a small installation business, covering intake, orders, inventory, payments, scheduling, technician ownership, follow-up and management reporting.",
    limitations: [
      "This is a design case study for a fictional company. There is no client deployment behind it.",
      "No time saving, payment recovery or delay reduction has been measured. Any figure of that kind would be invented.",
      "The business impact described is the intended operating model, not an audited outcome.",
    ],
    judgement: "The process problem was sequencing, not software. Scheduling before checking stock would have survived any tool purchase, so I fixed the handoff rule first and refused to attach a saving figure to a system nobody has run.",
  }
];
